# Generated by Django 3.1 on 2020-08-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200811_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
